// src/lib/components/Header.svelte
<script lang="ts" module>
	export const navLinks = [
		{ label: "Donate", href: "/donationspage" },
		{ label: "Donations", href: "/donationslist" },
		{ label: "About", href: "/about" }
	];
</script>

<script lang="ts">
	import { Button } from "$lib/components/ui/button";
	import { createScroll } from "$lib/hooks/useScroll.svelte";
	import Logo from "$lib/components/Logo.svelte";

	import { Portal, PortalBackdrop } from "$lib/components/ui/portal";
	import { cn } from "$lib/utils";
	import { MenuIcon, XIcon } from "@lucide/svelte";
	import ModeToggle from "$lib/components/modeToggle.svelte"

	let open = $state(false);
	let scroll = createScroll(10);
</script>

<header
	class={cn(
		"sticky top-0 z-50 mx-auto w-full max-w-4xl border-b border-transparent md:rounded-md md:border md:transition-all md:ease-out",
		scroll.scrolled &&
			"border-border bg-background/95 backdrop-blur-sm supports-backdrop-filter:bg-background/50 md:top-2 md:max-w-3xl md:shadow"
	)}
>
	<nav
		class={cn(
			"flex h-14 w-full items-center justify-between px-4 md:h-12 md:transition-all md:ease-out",
			scroll.scrolled && "md:px-2"
		)}
	>
		<a class="rounded-md p-2 hover:bg-muted dark:hover:bg-muted/50" href="/">
			<Logo class="h-4" />
		</a>
		<div class="hidden items-center gap-2 md:flex">
			<div>
				{#each navLinks as { label, href }}
					<Button size="sm" variant="ghost" {href}>
						{label}
					</Button>
				{/each}
			</div>
			<ModeToggle/>
		</div>
		<div class="md:hidden">
			<Button
				aria-controls="mobile-menu"
				aria-expanded={open}
				aria-label="Toggle menu"
				class="md:hidden"
				size="icon"
				variant="outline"
				onclick={() => (open = !open)}
			>
				{#if open}
					<XIcon class="size-4.5" />
				{:else}
					<MenuIcon class="size-4.5" />
				{/if}
			</Button>
			{#if open}
				<Portal class="top-14">
					<PortalBackdrop />
					<div
						class={cn(
							"ease-out data-[slot=open]:animate-in data-[slot=open]:zoom-in-97",
							"size-full p-4"
						)}
						data-slot={open ? "open" : "closed"}
					>
						<div class="grid gap-y-2">
							{#each navLinks as link, i}
								<Button class="justify-start" variant="ghost" href={link.href}>
									{link.label}
								</Button>
							{/each}
						</div>
						<div class="mt-12 flex flex-col gap-2">
						<ModeToggle/>
						</div>
					</div>
				</Portal>
			{/if}
		</div>
	</nav>
</header>

// src/components/header.tsx
import { useState } from "react";
// import ToggleDarkMode from "@/components/toggledarkmode";
import Link from "next/link";
import Logo from "@/components/logo";
import ToggleMenu from "@/components/togglemenu";
import { HeaderProps } from "@/lib/types";

export const headerData: HeaderProps = {
  links: [
    {
      label: "About us",
      href: "#",
    },
    {
      label: "Donations",
      href: "/donations",
    },
    {
      label: "Contact",
      href: "#",
    },
  ],

  isSticky: true,
  showToggleTheme: true,
  showRssFeed: false,
  position: "right",
};

const Header = () => {
  const { links, isSticky, showToggleTheme, showRssFeed, position } =
    headerData;

  const updatedIsDropdownOpen =
    links &&
    links.map(() => {
      return false;
    });

  const [isDropdownOpen, setIsDropdownOpen] = useState<boolean[]>(
    updatedIsDropdownOpen as boolean[]
  );
  const [isToggleMenuOpen, setIsToggleMenuOpen] = useState<boolean>(false);

  const handleDropdownOnClick = (index: number) => {
    setIsDropdownOpen((prevValues) => {
      const newValues = [...(prevValues as boolean[])];
      newValues.forEach((value, i) => {
        if (value === true) {
          newValues[i] = false;
        } else {
          newValues[i] = i === index;
        }
      });
      return newValues;
    });
  };

  const handleCloseDropdownOnClick = (index: number) => {
    setIsDropdownOpen((prevValues) => {
      const newValues = [...(prevValues as boolean[])];
      newValues[index] = false;
      return newValues;
    });
  };

  const handleToggleMenuOnClick = () => {
    setIsToggleMenuOpen(!isToggleMenuOpen);
  };

  return (
    <header
      className={`top-0 z-40 mx-auto w-full flex-none bg-white transition-all duration-100 ease-in dark:bg-slate-900 md:bg-white/90 md:backdrop-blur-sm dark:md:bg-slate-900/90 ${
        isSticky ? "sticky" : "relative"
      }`}
      id="header"
    >
      <div className="mx-auto w-full max-w-7xl py-3 px-3 md:flex md:justify-between md:py-3.5 md:px-4">
        <div className="flex justify-between">
          <Link
            className="flex items-center"
            href="/"
            onClick={() =>
              isToggleMenuOpen
                ? handleToggleMenuOnClick()
                : setIsDropdownOpen(updatedIsDropdownOpen as boolean[])
            }
          >
            <Logo />
          </Link>
          <div className="flex items-center md:hidden">
            <ToggleMenu
              handleToggleMenuOnClick={handleToggleMenuOnClick}
              isToggleMenuOpen={isToggleMenuOpen}
            />
          </div>
        </div>
        <nav
          className={`${
            isToggleMenuOpen ? "block" : "hidden"
          } h-screen md:w-full ${
            position === "right"
              ? "justify-end"
              : position === "left"
              ? "justify-start"
              : "justify-center"
          } w-auto overflow-y-auto dark:text-slate-200 md:mx-5 md:flex md:h-auto md:items-center md:overflow-visible`}
          aria-label="Main navigation"
        >
          <ul className="flex w-full flex-col pt-8 text-xl md:w-auto md:flex-row md:self-center md:pt-0 md:text-base">
            {links &&
              links.map(({ label, href, icon: Icon, links }, index) => (
                <li
                  key={`item-link-${index}`}
                  className={links?.length ? "dropdown" : ""}
                >
                  {links && links.length ? (
                    <>
                      <button
                        className="flex items-center px-4 py-3 font-medium transition duration-150 ease-in-out hover:text-gray-900 dark:hover:text-white"
                        onClick={() => handleDropdownOnClick(index)}
                      >
                        {label}{" "}
                        {Icon && (
                          <Icon className="ml-0.5 hidden h-3.5 w-3.5 md:inline" />
                        )}
                      </button>
                      <ul
                        className={`${
                          isDropdownOpen[index] ? "block" : "md:hidden"
                        } rounded pl-4 font-medium drop-shadow-xl md:absolute md:min-w-[200px] md:bg-white/90 md:pl-0 md:backdrop-blur-md dark:md:bg-slate-900/90`}
                      >
                        {links.map(({ label: label2, href: href2 }, index2) => (
                          <li key={`item-link-${index2}`}>
                            <Link
                              className="whitespace-no-wrap block py-2 px-5 first:rounded-t last:rounded-b dark:hover:bg-gray-700 md:hover:bg-gray-200"
                              href={href2 as string}
                              onClick={() =>
                                isToggleMenuOpen
                                  ? handleToggleMenuOnClick()
                                  : handleCloseDropdownOnClick(index)
                              }
                            >
                              {label2}
                            </Link>
                          </li>
                        ))}
                      </ul>
                    </>
                  ) : (
                    <Link
                      className="flex items-center px-4 py-3 font-medium transition duration-150 ease-in-out hover:text-gray-900 dark:hover:text-white"
                      href={href as string}
                      onClick={() =>
                        isToggleMenuOpen
                          ? handleToggleMenuOnClick()
                          : handleDropdownOnClick(index)
                      }
                    >
                      {label}
                    </Link>
                  )}
                </li>
              ))}
          </ul>
        </nav>
        <div
          className={`${
            isToggleMenuOpen ? "block" : "hidden"
          } fixed bottom-0 left-0 w-full justify-end p-3 md:static md:mb-0 md:flex md:w-auto md:self-center md:p-0`}
        >
          {/* <div className="flex w-full items-center justify-between md:w-auto">
            {showToggleTheme && <ToggleDarkMode />}
            {showRssFeed && (
              <Link
                className="text-muted inline-flex items-center rounded-lg p-2.5 text-sm hover:bg-gray-100 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-700"
                aria-label="RSS Feed"
                href=""
              >
                <ArchiveIcon className="h-5 w-5" />
              </Link>
            )} */}
          {/* {actions && actions.length > 0 && (
              <div className="ml-4 flex w-max flex-wrap justify-end">
                {actions.map((callToAction, index) => (
                  <CTA
                    key={`item-action-${index}`}
                    data={callToAction as CallToAction}
                    class="m-1 py-2 px-5 text-sm font-semibold shadow-none md:px-6"
                  />
                ))}
              </div>
            )} */}
        </div>
        {/* </div> */}
      </div>
    </header>
  );
};

export default Header;
