// src/components/recentDonations.tsx
import Image from "next/image";
import { MoreHorizontal } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import Link from "next/link";
import Airtable from "airtable";

export default function Donations() {
  const [records, setRecords] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
const baseId= process.env.AIRTABLE_BASE_ID
  useEffect(() => {
    const base = new Airtable({ apiKey: process.env.AIRTABLE_API_KEY }).base(baseId);

    base("Table Name")
      .select({
        // Specify sorting, filtering, and fields if necessary
      })
      .eachPage(
        (records, fetchNextPage) => {
          setRecords(records);
          fetchNextPage();
        },
        (err) => {
          if (err) {
            console.error(err);
            return;
          }
          setIsLoading(false);
        }
      );
  }, []);

  if (isLoading) return <div>Loading...</div>;

  return (
    <table>
      <tbody>
        {records.map((record) => (
          <TableRow key={record.id}>
            <TableCell className="hidden sm:table-cell">
              <Image
                alt="Product image"
                className="aspect-square rounded-md object-cover"
                height="64"
                src={record.fields.Image[0].url}
                width="64"
              />
            </TableCell>
            <TableCell className="font-medium">{record.fields.Name}</TableCell>
            <TableCell>
              <Badge variant="outline">{record.fields.Status}</Badge>
            </TableCell>
            <TableCell className="hidden md:table-cell">
              {record.fields.Price}
            </TableCell>
            <TableCell className="hidden md:table-cell">
              {record.fields.Quantity}
            </TableCell>
            <TableCell className="hidden md:table-cell">
              {record.fields.Date}
            </TableCell>
            <TableCell>{/* DropdownMenu for actions */}</TableCell>
          </TableRow>
        ))}
      </tbody>
    </table>
  );
}

// src/routes/donationslist/recentDonations.svelte
<script>
  import { onMount } from 'svelte';
  import Airtable from 'airtable';
  import { MoreHorizontal } from 'lucide-svelte';
  
  // Import shadcn-svelte components
  import { Badge } from '$lib/components/ui/badge';
  import { Button } from '$lib/components/ui/button';
  import { 
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuTrigger 
  } from '$lib/components/ui/dropdown-menu';
  import { 
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow 
  } from '$lib/components/ui/table';
  
  let records = [];
  let isLoading = true;
  
  onMount(() => {
    const apiKey = import.meta.env.VITE_AIRTABLE_API_KEY;
    const baseId = import.meta.env.VITE_AIRTABLE_BASE_ID;
    
    console.log(apiKey);
    console.log(baseId);
    if (!apiKey || !baseId) {
      console.error("Airtable API key or Base ID is undefined");
      isLoading = false;
      return;
    }
    
    const base = new Airtable({ apiKey }).base(baseId);
    
    base("Donors")
      .select({
        // Specify sorting, filtering, and fields if necessary
      })
      .eachPage(
        (fetchedRecords, fetchNextPage) => {
          records = fetchedRecords;
          fetchNextPage();
        },
        (err) => {
          if (err) {
            console.error(err);
            return;
          }
          isLoading = false;
        }
      );
  });
</script>

{#if isLoading}
  <div>Loading...</div>
{:else}
  <Table>
    <TableBody>
      {#each records as record (record.id)}
        <TableRow>
          <TableCell class="hidden sm:table-cell">
            <img
              alt="Product image"
              class="aspect-square rounded-md object-cover h-16 w-16"
              src={record.fields.Image[0].url || "/placeholder.svg"}
            />
          </TableCell>
          <TableCell class="font-medium">{record.fields.Name}</TableCell>
          <TableCell>
            <Badge variant="outline">{record.fields.Status}</Badge>
          </TableCell>
          <TableCell class="hidden md:table-cell">
            {record.fields.Price}
          </TableCell>
          <TableCell class="hidden md:table-cell">
            {record.fields.Quantity}
          </TableCell>
          <TableCell class="hidden md:table-cell">
            {record.fields.Date}
          </TableCell>
          <TableCell>
            <DropdownMenu>
              <DropdownMenuTrigger>
                <Button variant="ghost" class="h-8 w-8 p-0">
                  <span class="sr-only">Open menu</span>
                  <MoreHorizontal class="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Actions</DropdownMenuLabel>
                <DropdownMenuItem>View details</DropdownMenuItem>
                <DropdownMenuItem>Edit</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </TableCell>
        </TableRow>
      {/each}
    </TableBody>
  </Table>
{/if}
